import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard, Users2, ClipboardList, AlertTriangle, Target,
  HeartHandshake, MessagesSquare, ListChecks, FileText, BookOpen,
  Contact, Network, BarChart3, Stamp, Activity, GraduationCap,
  DoorOpen, Wallet, Clock, Trophy, HeartPulse, Globe2,
  Handshake, Shuffle, LayoutGrid, Brain, BadgeCheck, Inbox,
  PlaneTakeoff, Coins, LineChart, LifeBuoy, Megaphone, Sparkles, TrendingUp, Mic,
  Scale, ExternalLink as ExternalLinkIcon, Rocket, Swords, PiggyBank,
  Award, FlaskConical, Heart, Compass, Crown, Moon,
  Map as MapIcon,
  Plug, ScrollText, ShieldCheck, Building2, Bot, Database, Smile,
  GanttChart,
} from "lucide-react";

export type ToolCategory =
  | "dashboard"
  | "talent"          // 採用・入退社
  | "people"          // 社員・組織
  | "contract"        // 業務委託・外部契約
  | "performance"    // 評価・1on1・人材戦略
  | "engagement"     // サーベイ・表彰・研修・離職リスク
  | "labor"          // 労務・コンプライアンス
  | "compensation"   // 報酬
  | "support"        // ヘルプデスク・目安箱
  | "admin";         // 管理者・連携・監査

export type ToolDef = {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  href: string;
  category: ToolCategory;
  keywords: string[];
  status: "ready" | "beta" | "planned";
  requiresRole?: ("hr_admin" | "manager" | "executive")[];
  audience?: ("everyone" | "manager" | "hr_admin" | "executive")[];
};

export const TOOLS: ToolDef[] = [
  // ─── ダッシュボード ───────────────
  {
    id: "portal",
    name: "HRポータル",
    description: "今日の予定・お知らせ・KPI を一画面で確認できるパーソナルダッシュボード",
    icon: LayoutDashboard,
    href: "/portal",
    category: "dashboard",
    keywords: ["ダッシュボード", "ホーム", "ポータル", "お知らせ"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "action-extractor",
    name: "AI 議事録 → アクション抽出",
    description: "議事録から誰が何をいつまでにやるかを構造化抽出 → 1on1 / OKR / ヘルプデスク等に自動分配",
    icon: ListChecks,
    href: "/action-extractor",
    category: "support",
    keywords: ["議事録", "アクション", "タスク", "抽出", "ai", "1on1"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "team-health",
    name: "チーム健康度ダッシュボード",
    description: "マネージャー視点で自チームの離職リスク・OKR・1on1・ムード・wellbeing を 1 画面で",
    icon: HeartPulse,
    href: "/team-health",
    category: "performance",
    keywords: ["チーム", "健康度", "マネージャー", "ダッシュボード", "総合"],
    status: "ready",
    audience: ["manager", "hr_admin"],
  },
  {
    id: "career-path",
    name: "キャリアパス",
    description: "社員ごとの過去ロール × 現職 × 将来オプション。likelihood × horizon の 2 次元で可視化",
    icon: MapIcon,
    href: "/career-path",
    category: "performance",
    keywords: ["キャリア", "パス", "career", "ロール", "将来"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "talent-review",
    name: "タレントレビュー & サクセション",
    description: "9-box matrix（performance × potential）+ キーポジション × 後継候補。flight risk と空席リスクを警告",
    icon: Crown,
    href: "/talent-review",
    category: "performance",
    keywords: ["タレント", "9 box", "9-box", "サクセション", "後継", "succession", "review"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "perf-calibration",
    name: "評価キャリブレーション",
    description: "OKR 達成度 × 360° 他者評価で 4 象限分類。Stars / 単独成果 / チーム貢献 / 改善必要を可視化",
    icon: Scale,
    href: "/perf-calibration",
    category: "performance",
    keywords: ["calibration", "okr", "360", "散布図", "象限", "昇進判定"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin", "manager"],
  },
  {
    id: "advocacy",
    name: "社員アドボカシー",
    description: "外部発信（記事・登壇・ポッドキャスト・OSS）の一元管理。リーダーボード + 報奨ポイント",
    icon: Megaphone,
    href: "/advocacy",
    category: "engagement",
    keywords: ["advocacy", "発信", "登壇", "記事", "リーダーボード", "報奨"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "coaching",
    name: "AI コーチング",
    description: "GROW モデルベースの月次コーチング会話を AI 生成。アドバイスではなく問い中心",
    icon: Brain,
    href: "/coaching",
    category: "engagement",
    keywords: ["coaching", "コーチング", "grow", "問い", "対話"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "wellbeing",
    name: "ウェルビーイング",
    description: "睡眠・ストレス・運動・ムードの自己申告ダッシュボード。個人 + 集約ビュー（N≥5 で匿名）",
    icon: Moon,
    href: "/wellbeing",
    category: "engagement",
    keywords: ["wellbeing", "睡眠", "ストレス", "運動", "ムード", "健康"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "three-sixty",
    name: "360° 評価",
    description: "本人・マネージャー・同僚・部下の 4 視点で多面評価。Self vs Others ギャップでブラインドスポット検出",
    icon: Compass,
    href: "/three-sixty",
    category: "performance",
    keywords: ["360", "多面評価", "blind spot", "ピア", "ギャップ"],
    status: "ready",
    audience: ["hr_admin", "manager"],
  },
  {
    id: "engagement-deep",
    name: "エンゲージメント深掘り",
    description: "在籍ステージ別の離脱要因分析。6 ドライバー × 退職クラスタリングで根本原因特定",
    icon: Activity,
    href: "/engagement-deep",
    category: "engagement",
    keywords: ["engagement", "ドライバー", "離脱", "ステージ", "退職理由"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "comp-bands",
    name: "報酬グレード制度",
    description: "自社レンジ × 市場ベンチマーク（25/50/75 percentile）でグレードの市場ポジション判定",
    icon: Coins,
    href: "/comp-bands",
    category: "compensation",
    keywords: ["報酬", "グレード", "市場ベンチマーク", "salary band", "lag", "lead"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "learning",
    name: "学習プラットフォーム",
    description: "スキルマトリクス × ラーニングパス × 社内勉強会。Udemy / Coursera / 書籍を統合",
    icon: GraduationCap,
    href: "/learning",
    category: "engagement",
    keywords: ["学習", "スキル", "ラーニング", "udemy", "coursera", "勉強会"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "diversity",
    name: "D&I 深掘り",
    description: "国籍・拠点・グレード・採用ファネルでダイバーシティを可視化。昇進機会の格差を検出",
    icon: Heart,
    href: "/diversity",
    category: "engagement",
    keywords: ["diversity", "inclusion", "d&i", "ダイバーシティ", "国籍", "外国籍", "格差"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "hr-dashboard",
    name: "HRダッシュボード",
    description: "ヘッドカウント・多様性・コスト・トレンドの統合分析。経営層向け",
    icon: BarChart3,
    href: "/hr-dashboard",
    category: "dashboard",
    keywords: ["分析", "KPI", "多様性", "ヘッドカウント"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },

  // ─── 採用・入退社 ─────────────────
  {
    id: "recruiting",
    name: "採用管理",
    description: "候補者パイプラインをカンバン形式で管理。リファラル・業務委託転換・面接評価・オファー連携まで",
    icon: ClipboardList,
    href: "/recruiting",
    category: "talent",
    keywords: ["採用", "ATS", "候補者", "パイプライン", "面接", "リファラル"],
    status: "ready",
    audience: ["hr_admin", "manager"],
  },
  {
    id: "onboarding-ai",
    name: "オンボーディング AI",
    description: "入社者プロフィールから 30/60/90 日プラン自動生成 + バディ自動マッチ",
    icon: Rocket,
    href: "/onboarding-ai",
    category: "talent",
    keywords: ["オンボーディング", "90日プラン", "バディ", "ai", "新入社員"],
    status: "ready",
    audience: ["hr_admin", "manager"],
  },
  {
    id: "recruiting-roi",
    name: "採用予算 ROI 分析",
    description: "予算 vs 実績 + 採用品質（90/180/365 日 retention + マネージャー評価）で経路の真の ROI を測定",
    icon: Award,
    href: "/recruiting-roi",
    category: "talent",
    keywords: ["roi", "投資対効果", "retention", "実績", "予算", "品質", "経路"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "offer-ab",
    name: "オファー A/B テスト",
    description: "複数バリアントを並行配信して受諾率を改善。z-test で統計的有意性も判定",
    icon: FlaskConical,
    href: "/offer-ab",
    category: "talent",
    keywords: ["ab テスト", "オファー", "受諾率", "勝者", "有意性"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "recruiting-budget",
    name: "採用予算シミュレータ",
    description: "採用人数 × 経路 × 平均コストで 12 ヶ月予算を試算。CSV エクスポート可",
    icon: PiggyBank,
    href: "/recruiting-budget",
    category: "talent",
    keywords: ["予算", "コスト", "cph", "シミュレータ", "試算", "月次"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "competitor-analysis",
    name: "競合分析",
    description: "他社 JD・採用条件と自社 JD の差分。給与競争力・スキル要件・福利厚生をベンチマーク",
    icon: Swords,
    href: "/competitor-analysis",
    category: "talent",
    keywords: ["競合", "ベンチマーク", "他社", "jd", "比較", "給与"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "talent-pool",
    name: "タレントプール CRM",
    description: "過去応募者・アルムナイ・カジュアル面談者・銀メダル候補の再アクティベート + AI で再アプローチ文生成",
    icon: Users2,
    href: "/talent-pool",
    category: "talent",
    keywords: ["タレントプール", "crm", "アルムナイ", "カジュアル", "再アプローチ", "アクティベート"],
    status: "ready",
    audience: ["hr_admin", "manager"],
  },
  {
    id: "interview-calibration",
    name: "面接官 Calibration",
    description: "複数面接官のスコア偏り分析（甘い・厳しい・バラツキ大）、軸別ヒートマップ、ペア合意度",
    icon: Scale,
    href: "/interview-calibration",
    category: "talent",
    keywords: ["calibration", "面接官", "バイアス", "偏り", "評価", "公平性"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "recruiting-kpi",
    name: "採用 KPI ダッシュボード",
    description: "時間 × 経路 × ロールの 3 次元ピボット分析。応募・採用・採用率・所要日数を自由切替",
    icon: BarChart3,
    href: "/recruiting-kpi",
    category: "talent",
    keywords: ["kpi", "ダッシュボード", "ピボット", "ヒートマップ", "採用分析", "経路", "ロール"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "careers-public",
    name: "公開採用ページ",
    description: "/careers の候補者向け公開ランディング（求人一覧・JD・応募フォーム）。Google for Jobs 対応",
    icon: ExternalLinkIcon,
    href: "/careers" as never,
    category: "talent",
    keywords: ["careers", "応募フォーム", "公開", "ランディング", "ats", "外部"],
    status: "ready",
    audience: ["hr_admin"],
  },
  {
    id: "interview-assistant",
    name: "AI 面接官アシスタント",
    description: "面接前のブリーフィング自動生成 + 面接中のリアルタイム質問サジェスト + タイマー + コンピテンシー追跡",
    icon: Mic,
    href: "/interview-assistant",
    category: "talent",
    keywords: ["面接", "interview", "AI", "アシスタント", "質問", "ブリーフィング", "サジェスト"],
    status: "ready",
    audience: ["hr_admin", "manager"],
  },
  {
    id: "recruiting-funnel",
    name: "母集団分析",
    description: "応募経路ごとの転換率・面接パスレート・採用率の歴史トレンドを可視化",
    icon: TrendingUp,
    href: "/recruiting-funnel",
    category: "talent",
    keywords: ["ファネル", "CVR", "母集団", "分析", "経路", "リファラル", "ボトルネック"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "recruiting-referral",
    name: "リファラル強化",
    description: "社員ごとに「あなたが知ってそうな候補者」を AI でサジェスト。ワンクリックで Slack 依頼 DM",
    icon: HeartHandshake,
    href: "/recruiting-referral",
    category: "talent",
    keywords: ["リファラル", "リファラ", "紹介", "知人", "ネットワーク", "AI", "サジェスト"],
    status: "ready",
    audience: ["hr_admin", "manager"],
  },
  {
    id: "recruiting-strategy",
    name: "戦略採用",
    description: "事業計画 × 現組織のスキルギャップから、未来の組織に必要な人材を AI でリコメンド",
    icon: Sparkles,
    href: "/recruiting-strategy",
    category: "talent",
    keywords: ["戦略", "採用計画", "ヘッドカウント", "AI", "組織設計", "人材戦略", "ギャップ"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "recruiting-branding",
    name: "採用広報",
    description: "AI で JD 生成 + Wantedly/LinkedIn/X/Indeed/Facebook 向け投稿テキストを一括リライト",
    icon: Megaphone,
    href: "/recruiting-branding",
    category: "talent",
    keywords: ["JD", "求人票", "Wantedly", "LinkedIn", "広報", "リライト", "ブランディング"],
    status: "ready",
    audience: ["hr_admin"],
  },
  {
    id: "offer-letter",
    name: "オファーレター生成",
    description: "候補者情報と条件を入れるだけで日本語/英語の内定通知書をPDF生成",
    icon: FileText,
    href: "/offer-letter",
    category: "talent",
    keywords: ["オファー", "内定通知書", "PDF"],
    status: "ready",
    audience: ["hr_admin"],
  },
  {
    id: "onboarding",
    name: "オンボーディング",
    description: "入社前〜90日目までの5フェーズチェックリスト。HR・マネージャー・バディで分担管理。Slack/Calendar 連携",
    icon: ListChecks,
    href: "/onboarding",
    category: "talent",
    keywords: ["オンボーディング", "入社", "新入社員", "チェックリスト"],
    status: "ready",
    audience: ["hr_admin", "manager"],
  },
  {
    id: "offboarding",
    name: "オフボーディング",
    description: "退職手続きチェックリスト・引き継ぎ管理・分析",
    icon: DoorOpen,
    href: "/offboarding",
    category: "talent",
    keywords: ["退職", "オフボーディング", "引き継ぎ"],
    status: "ready",
    audience: ["hr_admin", "manager"],
  },

  // ─── 社員・組織 ───────────────────
  {
    id: "directory",
    name: "社員名簿",
    description: "全社員のプロフィール・連絡先・スキル・Slackをカード形式で検索",
    icon: Contact,
    href: "/directory",
    category: "people",
    keywords: ["名簿", "ディレクトリ", "メンバー", "連絡先"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "orgchart",
    name: "組織図",
    description: "レポーティングライン・部門別・拠点国別の3ビューで組織構造を可視化",
    icon: Network,
    href: "/orgchart",
    category: "people",
    keywords: ["組織図", "オルグチャート", "部門", "拠点", "国別"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "alumni",
    name: "アルムナイ管理",
    description: "退職者ネットワーク・リファラル候補・カムバック採用を一元管理",
    icon: Globe2,
    href: "/alumni",
    category: "people",
    keywords: ["アルムナイ", "OBOG", "リファラル", "再雇用"],
    status: "ready",
    audience: ["hr_admin"],
  },
  {
    id: "org-management",
    name: "組織管理",
    description: "異動・配置・降格昇格の辞令を発行・履歴管理。組織変更シミュレーションも",
    icon: Shuffle,
    href: "/org-management",
    category: "people",
    keywords: ["異動", "配置", "辞令", "組織変更", "transfer", "部署", "department", "組織"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },

  // ─── 契約・委託 ───────────────────
  {
    id: "contractors",
    name: "業務委託管理",
    description: "国内・海外の業務委託パートナーを一元管理。契約期限・支払・成果物・NDAまで",
    icon: Handshake,
    href: "/contractors",
    category: "contract",
    keywords: ["業務委託", "フリーランス", "委託", "請負", "外注", "海外", "contractor"],
    status: "ready",
    requiresRole: ["hr_admin", "manager"],
    audience: ["hr_admin", "manager"],
  },

  // ─── 評価・人材戦略 ──────────────
  {
    id: "oneonone",
    name: "1on1マネージャー",
    description: "メンバーとの定期1on1を記録・管理。気分トレンド・アクション追跡・スケジュール調整",
    icon: MessagesSquare,
    href: "/oneonone",
    category: "performance",
    keywords: ["1on1", "面談", "アクションアイテム", "気分", "ムード"],
    status: "ready",
    audience: ["manager"],
  },
  {
    id: "mbo-okr",
    name: "MBO×OKR評価",
    description: "会社・部署・個人の3階層OKR + S/A/B/C/D 5段階MBO評価。カスケード可視化と1on1連携",
    icon: Target,
    href: "/mbo-okr",
    category: "performance",
    keywords: ["OKR", "MBO", "目標", "評価", "四半期", "カスケード"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "team",
    name: "チーム管理",
    description: "マネージャー向け：自チームメンバーのリスク・1on1進捗・評価ステータス",
    icon: Users2,
    href: "/team",
    category: "performance",
    keywords: ["チーム", "マネージャー", "メンバー"],
    status: "ready",
    requiresRole: ["manager", "hr_admin"],
    audience: ["manager"],
  },
  {
    id: "retention-oneonone",
    name: "リスク連動1on1",
    description: "離職リスクスコアと1on1管理を統合。高リスク社員を優先表示",
    icon: HeartHandshake,
    href: "/retention-oneonone",
    category: "performance",
    keywords: ["リテンション", "1on1", "リスク連動"],
    status: "ready",
    requiresRole: ["hr_admin", "manager"],
    audience: ["manager", "hr_admin"],
  },
  {
    id: "succession",
    name: "サクセションプランニング",
    description: "9-boxマトリクスで後継者候補を可視化。キーポジションのリスクと人材プールを管理",
    icon: LayoutGrid,
    href: "/succession",
    category: "performance",
    keywords: ["後継者", "サクセション", "9-box", "タレントレビュー", "ハイポテンシャル"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },

  // ─── エンゲージメント ────────────
  {
    id: "retention",
    name: "離職リスクモニター",
    description: "6因子の集約分析で離職予兆を早期検知。1on1・サーベイ・給与帯のデータを統合",
    icon: AlertTriangle,
    href: "/retention",
    category: "engagement",
    keywords: ["離職", "リテンション", "エンゲージメント", "リスク"],
    status: "ready",
    requiresRole: ["hr_admin", "manager"],
    audience: ["manager", "hr_admin"],
  },
  {
    id: "pulse-survey",
    name: "パルスサーベイ",
    description: "月次パルス + 年次エンゲージメント。eNPS・部門別ヒートマップ・アクションプラン管理",
    icon: Activity,
    href: "/pulse-survey",
    category: "engagement",
    keywords: ["サーベイ", "エンゲージメント", "アンケート", "eNPS", "パルス"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "value-award",
    name: "バリューアワード",
    description: "6つの会社バリューでピアツーピア表彰。月間MVP・ランキング・Slack #praise 連携",
    icon: Trophy,
    href: "/value-award",
    category: "engagement",
    keywords: ["表彰", "バリュー", "ピアボーナス", "MVP"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "training",
    name: "研修・スキル管理",
    description: "スキルマトリクス・研修管理・ギャップ分析",
    icon: GraduationCap,
    href: "/training",
    category: "engagement",
    keywords: ["研修", "スキル", "学習", "L&D"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "wiki",
    name: "社内Wiki",
    description: "Markdown 形式の情報基盤。8カテゴリ・全文検索・ピン留め・関連ページ自動表示",
    icon: BookOpen,
    href: "/wiki",
    category: "engagement",
    keywords: ["wiki", "ナレッジ", "ドキュメント", "制度"],
    status: "ready",
    audience: ["everyone"],
  },

  // ─── 労務・コンプライアンス ──────
  {
    id: "attendance",
    name: "勤怠・休暇管理",
    description: "勤怠サマリー・残業アラート・休暇申請承認・36協定チェック",
    icon: Clock,
    href: "/attendance",
    category: "labor",
    keywords: ["勤怠", "休暇", "残業", "36協定", "有休"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "visa",
    name: "在留資格・ビザ管理",
    description: "外国籍社員の在留カード期限・更新進捗を一元管理。書類自動生成・国別ビュー・freee 連携",
    icon: Stamp,
    href: "/visa",
    category: "labor",
    keywords: ["在留資格", "ビザ", "外国籍", "期限"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "health-check",
    name: "健康診断管理",
    description: "定期健診の受診状況・結果・産業医面談・労安法令チェックを一元管理",
    icon: HeartPulse,
    href: "/health-check",
    category: "labor",
    keywords: ["健診", "健康診断", "産業医", "労安法"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "stress-check",
    name: "ストレスチェック",
    description: "年1回の法定ストレスチェックを実施・集計・高ストレス者対応まで一元管理",
    icon: Brain,
    href: "/stress-check",
    category: "labor",
    keywords: ["ストレスチェック", "メンタルヘルス", "労安法", "産業医"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "qualifications",
    name: "資格・免許管理",
    description: "業務に必要な資格・免許の保有状況・有効期限を管理。更新リマインドも",
    icon: BadgeCheck,
    href: "/qualifications",
    category: "labor",
    keywords: ["資格", "免許", "認定", "更新", "証明書"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["everyone"],
  },
  {
    id: "expat",
    name: "海外赴任管理",
    description: "海外駐在員の手当・税務・赴任期間・帯同家族を一元管理",
    icon: PlaneTakeoff,
    href: "/expat",
    category: "labor",
    keywords: ["海外赴任", "駐在", "expat", "出向", "海外手当"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin", "executive"],
  },

  // ─── 報酬 ─────────────────────────
  {
    id: "salary-band",
    name: "給与帯・昇給管理",
    description: "給与レンジ設定・市場ベンチマーク・昇給シミュレーション",
    icon: Wallet,
    href: "/salary-band",
    category: "compensation",
    keywords: ["給与", "報酬", "昇給", "コンプ"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "bonus",
    name: "賞与管理",
    description: "賞与原資の配賦・個別評価との連動・支給シミュレーション",
    icon: Coins,
    href: "/bonus",
    category: "compensation",
    keywords: ["賞与", "ボーナス", "インセンティブ", "業績連動"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "stock-options",
    name: "ストックオプション管理",
    description: "SO付与・行使状況・vesting・税制適格チェックを管理",
    icon: LineChart,
    href: "/stock-options",
    category: "compensation",
    keywords: ["SO", "ストックオプション", "RSU", "vesting", "持株"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },

  // ─── サポート ─────────────────────
  {
    id: "helpdesk",
    name: "HRヘルプデスク",
    description: "問い合わせをチケット化。SLA管理・FAQ・Slack連携・カテゴリ分析",
    icon: LifeBuoy,
    href: "/helpdesk",
    category: "support",
    keywords: ["ヘルプデスク", "問い合わせ", "チケット", "FAQ"],
    status: "ready",
    audience: ["everyone"],
  },
  {
    id: "voice-box",
    name: "目安箱・通報",
    description: "ハラスメント・コンプラ通報窓口。匿名通報・重大度別エスカレーション・社外弁護士連携",
    icon: Inbox,
    href: "/voice-box",
    category: "support",
    keywords: ["目安箱", "通報", "ハラスメント", "コンプライアンス", "匿名"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["everyone"],
  },
  // ───── admin（管理者・連携・監査） ─────
  {
    id: "employees-admin",
    name: "社員管理",
    description: "社員の追加・編集・退職処理・部署/上司の付替え。Phase B 新規",
    icon: Users2,
    href: "/admin/employees",
    category: "admin",
    keywords: ["社員", "従業員", "メンバー", "employee", "CRUD", "退職", "異動"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "departments-admin",
    name: "部署管理",
    description: "組織階層・部署マスタの追加編集・並べ替え。社員所属の集計も",
    icon: Network,
    href: "/admin/departments",
    category: "admin",
    keywords: ["部署", "組織", "階層", "departments"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "roles-admin",
    name: "権限管理",
    description: "hr_admin / manager / employee / executive 等のロール付与・剥奪",
    icon: ShieldCheck,
    href: "/admin/roles",
    category: "admin",
    keywords: ["権限", "ロール", "アクセス制御", "roles", "RBAC"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "integrations-admin",
    name: "連携設定",
    description: "freee / Slack / Google Workspace / Anthropic などの外部サービス連携",
    icon: Plug,
    href: "/admin/integrations",
    category: "admin",
    keywords: ["連携", "integration", "freee", "Slack", "Google", "API"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "audit-log-admin",
    name: "監査ログ",
    description: "全操作の監査証跡。誰が・いつ・何を変更したかを時系列追跡",
    icon: ScrollText,
    href: "/admin/audit-log",
    category: "admin",
    keywords: ["監査", "ログ", "audit", "履歴"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
  {
    id: "activity-stream-admin",
    name: "アクティビティ",
    description: "全社の最新活動ストリーム。承認・コメント・更新の集約ビュー",
    icon: Activity,
    href: "/admin/activity-stream",
    category: "admin",
    keywords: ["アクティビティ", "活動", "stream", "通知"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "ai-usage-admin",
    name: "AI 利用量",
    description: "Anthropic Claude / 各 AI 機能のトークン使用量・コスト・上限管理",
    icon: BarChart3,
    href: "/admin/ai-usage",
    category: "admin",
    keywords: ["AI", "利用量", "コスト", "Claude", "Anthropic", "usage"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "ai-agents-admin",
    name: "AI エージェント",
    description: "採用 AI・1on1 サマリ・退職予兆検知などの AI エージェント運用管理",
    icon: Bot,
    href: "/admin/ai-agents",
    category: "admin",
    keywords: ["AI", "エージェント", "agent", "自動化"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "hris-sync-admin",
    name: "HRIS 同期",
    description: "freee 人事労務などの HRIS と双方向同期。差分検出・コンフリクト解消",
    icon: GanttChart,
    href: "/admin/hris-sync",
    category: "admin",
    keywords: ["HRIS", "同期", "freee", "sync"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "data-lake-admin",
    name: "データレイク",
    description: "BigQuery / Snowflake 等への HR データ連携。分析チームへのデータ提供",
    icon: Database,
    href: "/admin/data-lake",
    category: "admin",
    keywords: ["データ", "lake", "BigQuery", "分析", "data"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "candidate-experience-admin",
    name: "候補者体験管理",
    description: "選考プロセスの候補者満足度・NPS 計測・改善アクション",
    icon: Smile,
    href: "/admin/candidate-experience",
    category: "admin",
    keywords: ["候補者", "体験", "NPS", "candidate"],
    status: "ready",
    requiresRole: ["hr_admin"],
    audience: ["hr_admin"],
  },
  {
    id: "competitor-pipeline-admin",
    name: "競合パイプライン",
    description: "競合他社の求人動向・採用ペースのウォッチ。タレントプール戦略立案",
    icon: Swords,
    href: "/admin/competitor-pipeline",
    category: "admin",
    keywords: ["競合", "パイプライン", "competitor"],
    status: "ready",
    requiresRole: ["hr_admin", "executive"],
    audience: ["hr_admin", "executive"],
  },
];

export const CATEGORY_LABELS: Record<ToolCategory, string> = {
  dashboard: "ダッシュボード",
  talent: "採用・入退社",
  people: "社員・組織",
  contract: "契約・委託",
  performance: "評価・人材戦略",
  engagement: "エンゲージメント",
  labor: "労務・コンプライアンス",
  compensation: "報酬",
  support: "サポート",
  admin: "管理者",
};

export const CATEGORY_ORDER: ToolCategory[] = [
  "dashboard", "talent", "people", "contract", "performance",
  "engagement", "labor", "compensation", "support", "admin",
];

export function toolsByCategory() {
  const map = new Map<ToolCategory, ToolDef[]>();
  for (const c of CATEGORY_ORDER) map.set(c, []);
  for (const tool of TOOLS) map.get(tool.category)!.push(tool);
  return map;
}

export function findTool(query: string): ToolDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return TOOLS;
  return TOOLS.filter((t) => {
    const haystack = [t.name, t.description, ...t.keywords].join(" ").toLowerCase();
    return haystack.includes(q);
  });
}
